name: deploy

on:
    push:
        branches: [master]

strategy:
    matrix:
        node-version: [10.16.0]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Push to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  script: cd /home/pi/compagnon && git pull
